// Auto-generated by /genpage Phase 0.5 (do not edit by hand).
//
// Provides type definitions for runtime globals injected by the Power Apps
// model-driven app shell. After this file exists alongside the page's .tsx,
// the page can use `window.Xrm.Navigation.navigateTo(...)` without
// `(window as any).` casts.
//
// Regenerate by running:
//   node ${PLUGIN_ROOT}/scripts/generate-page-manifest.js <dir> <slug> --force

export {};

declare global {
    /** Subset of Xrm v9 surface used by generative pages. Extend as needed. */
    interface XrmShape {
        Navigation: {
            navigateTo: (
                pageInput: XrmPageInput,
                navigationOptions?: { target?: 1 | 2 },
            ) => Promise<XrmNavigationResult>;
            openForm: (
                formOptions: { entityName: string; entityId?: string },
                formParameters?: Record<string, unknown>,
            ) => Promise<unknown>;
            openUrl: (url: string, options?: { target?: 1 | 2 }) => void;
        };
        Utility: {
            getGlobalContext: () => XrmGlobalContext;
        };
    }

    type XrmPageInput =
        | { pageType: 'entityrecord'; entityName: string; entityId?: string }
        | { pageType: 'entitylist'; entityName: string }
        | {
            pageType: 'custom';
            pageId: string;
            entityName?: string;
            recordId?: string;
            data?: Record<string, unknown>;
        }
        | {
            /** Cross-page navigation between generative pages — see rules.md PAGEREF_ placeholder. */
            pageType: 'generative';
            pageId: string;
            entityName?: string;
            recordId?: string;
            data?: Record<string, unknown>;
        };

    interface XrmNavigationResult {
        savedEntityReference?: Array<{ entityType: string; id: string; name?: string }>;
    }

    interface XrmGlobalContext {
        userSettings: {
            userId: string;
            userName: string;
            languageId: number;
            dateFormattingInfo?: Record<string, unknown>;
        };
        organizationSettings: {
            organizationId: string;
            languageId: number;
            baseCurrency?: { id: string };
        };
        getClientUrl: () => string;
    }

    interface Window {
        /** Provided by the model-driven app shell. */
        Xrm: XrmShape;
    }

    /**
     * Bare `Xrm` identifier (used by generated pages as `Xrm.Navigation...`
     * without the `window.` prefix). Same shape as `window.Xrm`.
     */
    const Xrm: XrmShape;

    /**
     * Per-page cache keys MUST follow the pattern `__genpage_<entity>_<v>`
     * (see references/data-caching.md). The string-key index signature lets
     * TypeScript accept dynamic cache reads/writes without `(window as any)`.
     */
    interface Window {
        [cacheKey: `__genpage_${string}`]: unknown;
    }
}
